[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
numReplicas = 1

[nixpacks]
nodejs_version = "18"
setup = ["apt-get update", "apt-get install -y sqlite3"]
