[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "NODE_ENV=production node server.js"
restartPolicyType = "on_failure"

[nixpacks]
nodejs_version = "18"

[[build.env]]
key = "NODE_ENV"
value = "production"
